# This file was automatically generated by Sbtix. Do not edit manually.
{
  "versioning" = [{
      "scalaVersion" = "2.10.6";
      "sbtVersion" = "0.13.15";
    }];
  "repos" = {
    "nix-public" = "";
    "nix-typesafe-ivy-releases" = "[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]";
  };
  "artifacts" = {
    "nix-public/com/jcraft/jsch/0.1.50/jsch-0.1.50.jar" = {
      url = "https://repo1.maven.org/maven2/com/jcraft/jsch/0.1.50/jsch-0.1.50.jar";
      sha256 = "15di2xp89g3nw4shdmfl6vygqpx57ar8dyrz65d9qhjgx3yfgybx";
    };
    "nix-public/com/jcraft/jsch/0.1.50/jsch-0.1.50.pom" = {
      url = "https://repo1.maven.org/maven2/com/jcraft/jsch/0.1.50/jsch-0.1.50.pom";
      sha256 = "1c5x6zm8yfgbvbxlprlw03nz9m5bpd7n2bsapjnfvp7hbycksvjk";
    };
    "nix-public/com/lihaoyi/fastparse-utils_2.10/0.4.2/fastparse-utils_2.10-0.4.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/fastparse-utils_2.10/0.4.2/fastparse-utils_2.10-0.4.2.jar";
      sha256 = "0mngj6wpzqkx5fcvx8ljqshdmc2gn99j9r86nxm0kb4a7xvllk67";
    };
    "nix-public/com/lihaoyi/fastparse-utils_2.10/0.4.2/fastparse-utils_2.10-0.4.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/fastparse-utils_2.10/0.4.2/fastparse-utils_2.10-0.4.2.pom";
      sha256 = "0qp58mmikk3h2149px8h4aqa8vynhvxjw8d7i1c5ngwrd1804bmf";
    };
    "nix-public/com/lihaoyi/fastparse_2.10/0.4.2/fastparse_2.10-0.4.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/fastparse_2.10/0.4.2/fastparse_2.10-0.4.2.jar";
      sha256 = "1vlf62107nd9lq7d9sf6wymnmy94km1z03hi8fy5aqjxhxlacac2";
    };
    "nix-public/com/lihaoyi/fastparse_2.10/0.4.2/fastparse_2.10-0.4.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/fastparse_2.10/0.4.2/fastparse_2.10-0.4.2.pom";
      sha256 = "1b6g80hm5k4r1fhqr4rbz8j225hi8nylm5kqkph45d3gy93bf729";
    };
    "nix-public/com/lihaoyi/sourcecode_2.10/0.1.3/sourcecode_2.10-0.1.3.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/sourcecode_2.10/0.1.3/sourcecode_2.10-0.1.3.jar";
      sha256 = "0crghkb1kf2xnkvpgmggd2qbyzfcrqw47q4fgkk0nlc37j3ana0h";
    };
    "nix-public/com/lihaoyi/sourcecode_2.10/0.1.3/sourcecode_2.10-0.1.3.pom" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/sourcecode_2.10/0.1.3/sourcecode_2.10-0.1.3.pom";
      sha256 = "1b89psa2vrpwz9wbyf796wvqvfr5y0jz45w2mfr6nnqk45wzcaq3";
    };
    "nix-public/com/thoughtworks/paranamer/paranamer-parent/2.6/paranamer-parent-2.6.pom" = {
      url = "https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer-parent/2.6/paranamer-parent-2.6.pom";
      sha256 = "142n45rzlgjvjmb2aj9r6acvzf07vcfr2knwqxm3lmlanqbxkgjp";
    };
    "nix-public/com/thoughtworks/paranamer/paranamer/2.6/paranamer-2.6.jar" = {
      url = "https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.6/paranamer-2.6.jar";
      sha256 = "1grs2kfh9z5xn5h1z0dqiqbhj5l6k9ww6mbb42n3gzkmin2w2qxr";
    };
    "nix-public/com/thoughtworks/paranamer/paranamer/2.6/paranamer-2.6.pom" = {
      url = "https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.6/paranamer-2.6.pom";
      sha256 = "0jcnwq4yh2nzbsx1x1kvnxrs0xrznjclyfxg31nfrxdq1cqd66q5";
    };
    "nix-public/io/get-coursier/coursier-cache_2.10/1.0.0-M15-1/coursier-cache_2.10-1.0.0-M15-1.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-cache_2.10/1.0.0-M15-1/coursier-cache_2.10-1.0.0-M15-1.jar";
      sha256 = "1mkd0jk2vcvand6nh4wvz5fa1iqz6h80kbna0qvvq8nf2jqikpgm";
    };
    "nix-public/io/get-coursier/coursier-cache_2.10/1.0.0-M15-1/coursier-cache_2.10-1.0.0-M15-1.pom" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-cache_2.10/1.0.0-M15-1/coursier-cache_2.10-1.0.0-M15-1.pom";
      sha256 = "0n4ds90rhkkwh1gcxk6gdqf9xzky6xrx84b521yvb9fwh19za4da";
    };
    "nix-public/io/get-coursier/coursier_2.10/1.0.0-M15-1/coursier_2.10-1.0.0-M15-1.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier_2.10/1.0.0-M15-1/coursier_2.10-1.0.0-M15-1.jar";
      sha256 = "1zn06b6zl4wzikrf2qb3qm86gs4ddwkmkw9v824ygssa7sg1wz80";
    };
    "nix-public/io/get-coursier/coursier_2.10/1.0.0-M15-1/coursier_2.10-1.0.0-M15-1.pom" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier_2.10/1.0.0-M15-1/coursier_2.10-1.0.0-M15-1.pom";
      sha256 = "1vvz6kd1dvdsshn0l29s4w8lsa32l3msjl7f7admvar4w4sa152n";
    };
    "nix-public/io/get-coursier/sbt-coursier_2.10_0.13/1.0.0-M15-1/sbt-coursier-1.0.0-M15-1.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/sbt-coursier_2.10_0.13/1.0.0-M15-1/sbt-coursier-1.0.0-M15-1.jar";
      sha256 = "0llilxqhpaabkbl7xjq4ric5kmrmfqny2mias7y4cqygkbaz56h4";
    };
    "nix-public/io/get-coursier/sbt-coursier_2.10_0.13/1.0.0-M15-1/sbt-coursier-1.0.0-M15-1.pom" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/sbt-coursier_2.10_0.13/1.0.0-M15-1/sbt-coursier-1.0.0-M15-1.pom";
      sha256 = "131nq3qiqiqc4qy2435y1cy8ljd6d7811cqpda4vf1v9aj11vsqp";
    };
    "nix-public/jline/jline/2.14.3/jline-2.14.3.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.3/jline-2.14.3.jar";
      sha256 = "0912i3cn9f357dbk005pv1n0jvyb4s8bz1jspn1jqnvbszzjdp7q";
    };
    "nix-public/jline/jline/2.14.3/jline-2.14.3.pom" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.3/jline-2.14.3.pom";
      sha256 = "1ics4ipmhnz93j0rprydxq306f2zldpywl2xmaqg4mxi38rq1hby";
    };
    "nix-public/org/codehaus/codehaus-parent/4/codehaus-parent-4.pom" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/codehaus-parent/4/codehaus-parent-4.pom";
      sha256 = "1pqlw2ilzagcl5ahq9dv60cxw59yrvrwf9q6z0679qf2x1yj71vb";
    };
    "nix-public/org/json4s/json4s-ast_2.10/3.2.10/json4s-ast_2.10-3.2.10.jar" = {
      url = "https://repo1.maven.org/maven2/org/json4s/json4s-ast_2.10/3.2.10/json4s-ast_2.10-3.2.10.jar";
      sha256 = "1agaxq0i9gplr932sq5c1raa0da30d83ckyylvqxgxmdf9kr8d8x";
    };
    "nix-public/org/json4s/json4s-ast_2.10/3.2.10/json4s-ast_2.10-3.2.10.pom" = {
      url = "https://repo1.maven.org/maven2/org/json4s/json4s-ast_2.10/3.2.10/json4s-ast_2.10-3.2.10.pom";
      sha256 = "10a5ccin3d6g37qja0g1yip5nbm18xbglbd8g88ml7z810sx48vr";
    };
    "nix-public/org/json4s/json4s-core_2.10/3.2.10/json4s-core_2.10-3.2.10.jar" = {
      url = "https://repo1.maven.org/maven2/org/json4s/json4s-core_2.10/3.2.10/json4s-core_2.10-3.2.10.jar";
      sha256 = "0d2i33ljkk96dyhv799dy198yn4k0ib04qbs7rk616l4mh0fxik3";
    };
    "nix-public/org/json4s/json4s-core_2.10/3.2.10/json4s-core_2.10-3.2.10.pom" = {
      url = "https://repo1.maven.org/maven2/org/json4s/json4s-core_2.10/3.2.10/json4s-core_2.10-3.2.10.pom";
      sha256 = "1fhzpzpx9xk9lx8m3za793qf8kwipc4cs338865z6k3wg8xdhvv9";
    };
    "nix-public/org/jsoup/jsoup/1.9.2/jsoup-1.9.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/jsoup/jsoup/1.9.2/jsoup-1.9.2.jar";
      sha256 = "0sm4s1a8plb8z5467799jvp0s37dr98q82z3y436w9c2n7qqa64w";
    };
    "nix-public/org/jsoup/jsoup/1.9.2/jsoup-1.9.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/jsoup/jsoup/1.9.2/jsoup-1.9.2.pom";
      sha256 = "0zh9xn8qcgjyhki5kbhb3rhbhd12avwqy6n9fqfzymdq3c41k8lk";
    };
    "nix-public/org/scala-lang/modules/scala-pickling_2.10/0.10.1/scala-pickling_2.10-0.10.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-pickling_2.10/0.10.1/scala-pickling_2.10-0.10.1.jar";
      sha256 = "0p6wa4brziq40vaqacijgg8xn2cpazv1sfngv0h618wnqk4q429y";
    };
    "nix-public/org/scala-lang/modules/scala-pickling_2.10/0.10.1/scala-pickling_2.10-0.10.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-pickling_2.10/0.10.1/scala-pickling_2.10-0.10.1.pom";
      sha256 = "1rc5c9xca1qbqibryv5k8a51pvhf4zpnxcvwrswzwc0afjkynfmw";
    };
    "nix-public/org/scala-lang/scala-compiler/2.10.6/scala-compiler-2.10.6.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.10.6/scala-compiler-2.10.6.jar";
      sha256 = "0fzwhlw9pl92b3mgci85qqz8s0fdci9dyh28lnjcdcjxpqrmjbpb";
    };
    "nix-public/org/scala-lang/scala-compiler/2.10.6/scala-compiler-2.10.6.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.10.6/scala-compiler-2.10.6.pom";
      sha256 = "0spli5785blg6q9rhgh10vgwk01v69zs3ncn1sam5rzbwpkhashi";
    };
    "nix-public/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.jar";
      sha256 = "0fy2i38z5x4xhw70rlsj33ddg225f15jr9ldbdq3gh59d1fvzqkr";
    };
    "nix-public/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.pom";
      sha256 = "0rr50x93xg480961s0ppyfd5ilcrmdw3rdz29y3dfnrmap99vl34";
    };
    "nix-public/org/scala-lang/scala-reflect/2.10.4/scala-reflect-2.10.4.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.10.4/scala-reflect-2.10.4.jar";
      sha256 = "1c5yskzv65n3n58hgggiaqgaxf3w8l31pq5ch6vqfk7ah9lvrbf3";
    };
    "nix-public/org/scala-lang/scala-reflect/2.10.4/scala-reflect-2.10.4.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.10.4/scala-reflect-2.10.4.pom";
      sha256 = "0h5n2fk69xwkliv3xnp8v8n3rpcaiznixdpa9w9raxmrs4wcgf5p";
    };
    "nix-public/org/scala-lang/scala-reflect/2.10.6/scala-reflect-2.10.6.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.10.6/scala-reflect-2.10.6.jar";
      sha256 = "0vgdn6mzzxqwrai1hsjcpsjxqnn38nv1caw6mhmwh3q4zq8jd7xb";
    };
    "nix-public/org/scala-lang/scala-reflect/2.10.6/scala-reflect-2.10.6.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.10.6/scala-reflect-2.10.6.pom";
      sha256 = "1085xmln652gzf3dn2hvyhnfx9pnwsipb54jr5rdxqm30pb1p8i3";
    };
    "nix-public/org/scala-sbt/ivy/ivy/2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/ivy/ivy/2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar";
      sha256 = "0fcqkj3vg2mfmcjahm2z8wy3lfbgq567n7kkjs8135yiwr0ws6m5";
    };
    "nix-public/org/scala-sbt/ivy/ivy/2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/ivy/ivy/2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.pom";
      sha256 = "0hlkyxivan8wi6vfl19mwppig887qpjdyljjin668zpg6a8hgn2h";
    };
    "nix-public/org/scala-sbt/launcher-interface/1.0.1/launcher-interface-1.0.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/launcher-interface/1.0.1/launcher-interface-1.0.1.jar";
      sha256 = "0zby99mp7mf5ra95a0536kl7f8y972a1ldqjhrj88yhw1mgfyxkp";
    };
    "nix-public/org/scala-sbt/launcher-interface/1.0.1/launcher-interface-1.0.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/launcher-interface/1.0.1/launcher-interface-1.0.1.pom";
      sha256 = "0ysandpwxf1rh7dpzxr07a8527sdssx8hqd2396yqw3hwp9jkdrd";
    };
    "nix-public/org/scala-sbt/serialization_2.10/0.1.2/serialization_2.10-0.1.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/serialization_2.10/0.1.2/serialization_2.10-0.1.2.jar";
      sha256 = "0n6j469ldrwlhdk9rz95q87ky3wb5m87g9nwlmxb8qvbrlkz37r4";
    };
    "nix-public/org/scala-sbt/serialization_2.10/0.1.2/serialization_2.10-0.1.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/serialization_2.10/0.1.2/serialization_2.10-0.1.2.pom";
      sha256 = "19fw8dlfiy333rdxqnys59nrnn5wj4fmy1srflyrlw6nf0hlfbwm";
    };
    "nix-public/org/scala-sbt/template-resolver/0.1/template-resolver-0.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/template-resolver/0.1/template-resolver-0.1.jar";
      sha256 = "0mkw92467i4jip5kbzvl5v1zwzv05alb3hb97l6z9bp641mxbf0b";
    };
    "nix-public/org/scala-sbt/template-resolver/0.1/template-resolver-0.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/template-resolver/0.1/template-resolver-0.1.pom";
      sha256 = "0nsx88y1b3nqpd6r80bb1rpaaskfhcxdbfaqngykrxz8gvq3i2q3";
    };
    "nix-public/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar";
      sha256 = "17klrl4ylpsy9d16fk6npb7lxfqr1w1m9slsxhph1wwmpcw0pxqm";
    };
    "nix-public/org/scala-sbt/test-interface/1.0/test-interface-1.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.pom";
      sha256 = "0bknid634xcq5r8fs1bx0ydxs3rhzgmzq1400h7y29n2s2lhdfk1";
    };
    "nix-public/org/scalamacros/quasiquotes_2.10/2.0.1/quasiquotes_2.10-2.0.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalamacros/quasiquotes_2.10/2.0.1/quasiquotes_2.10-2.0.1.jar";
      sha256 = "0hmz6viibw9jlzzv30kamp18wb30hlilh6nz6w6xvx8jpzx8f7jq";
    };
    "nix-public/org/scalamacros/quasiquotes_2.10/2.0.1/quasiquotes_2.10-2.0.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalamacros/quasiquotes_2.10/2.0.1/quasiquotes_2.10-2.0.1.pom";
      sha256 = "1b04njqa804m3mf946q92ljb5nqi42cc61xw58r3dhdqvq60gajv";
    };
    "nix-public/org/scalamacros/quasiquotes_2.10/2.1.0/quasiquotes_2.10-2.1.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalamacros/quasiquotes_2.10/2.1.0/quasiquotes_2.10-2.1.0.jar";
      sha256 = "11savihn3l4i4q7s3wjadzszr6g1f71v2hnc5vqgshd0islyxfa0";
    };
    "nix-public/org/scalamacros/quasiquotes_2.10/2.1.0/quasiquotes_2.10-2.1.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalamacros/quasiquotes_2.10/2.1.0/quasiquotes_2.10-2.1.0.pom";
      sha256 = "03k66gjsvq1ycfi32sn6wcs374cii130wzvv7ahjcfbqbg3f6j5f";
    };
    "nix-public/org/scalaz/scalaz-concurrent_2.10/7.2.7/scalaz-concurrent_2.10-7.2.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalaz/scalaz-concurrent_2.10/7.2.7/scalaz-concurrent_2.10-7.2.7.jar";
      sha256 = "0gnz0mhym3g8175g5rbibik5mc345xc25ig662c6npms364qwiwl";
    };
    "nix-public/org/scalaz/scalaz-concurrent_2.10/7.2.7/scalaz-concurrent_2.10-7.2.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalaz/scalaz-concurrent_2.10/7.2.7/scalaz-concurrent_2.10-7.2.7.pom";
      sha256 = "1yha06bwn7jig4i4h6a00wmngl23r0fnp0g5xfcpxwpn813z34s1";
    };
    "nix-public/org/scalaz/scalaz-core_2.10/7.2.7/scalaz-core_2.10-7.2.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalaz/scalaz-core_2.10/7.2.7/scalaz-core_2.10-7.2.7.jar";
      sha256 = "1cqqx9gj962i40ym85ldgkivb9499b9bbdlrw9yv6gib72g2ym26";
    };
    "nix-public/org/scalaz/scalaz-core_2.10/7.2.7/scalaz-core_2.10-7.2.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalaz/scalaz-core_2.10/7.2.7/scalaz-core_2.10-7.2.7.pom";
      sha256 = "0y4x8p18q30m95gxb0va8s5kf5crvw196wx6snnhqz7ldhzqlibx";
    };
    "nix-public/org/scalaz/scalaz-effect_2.10/7.2.7/scalaz-effect_2.10-7.2.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalaz/scalaz-effect_2.10/7.2.7/scalaz-effect_2.10-7.2.7.jar";
      sha256 = "179gfapgx4jjfqkd6aqx3lcbd9xk3grjxql1nd70vhy2f3sk58jb";
    };
    "nix-public/org/scalaz/scalaz-effect_2.10/7.2.7/scalaz-effect_2.10-7.2.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalaz/scalaz-effect_2.10/7.2.7/scalaz-effect_2.10-7.2.7.pom";
      sha256 = "0kqgcs5nb1v0vzasc8iciwkzrzxpjk3msxh9nldfmsnc4ga9dds0";
    };
    "nix-public/org/sonatype/oss/oss-parent/6/oss-parent-6.pom" = {
      url = "https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/6/oss-parent-6.pom";
      sha256 = "16c4i8n978zfb788i6lrwv9b6qgirzqnc25kl5c28fgmx09nsc5l";
    };
    "nix-public/org/sonatype/oss/oss-parent/9/oss-parent-9.pom" = {
      url = "https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom";
      sha256 = "0yl2hbwz2kn1hll1i00ddzn8f89bfdcjwdifz0pj2j15k1gjch7v";
    };
    "nix-public/org/spire-math/jawn-parser_2.10/0.6.0/jawn-parser_2.10-0.6.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/spire-math/jawn-parser_2.10/0.6.0/jawn-parser_2.10-0.6.0.jar";
      sha256 = "0p2g6lcqks4pycv8wr34i6cz9gvv71qv7ngv1rrihgj37jrapcg0";
    };
    "nix-public/org/spire-math/jawn-parser_2.10/0.6.0/jawn-parser_2.10-0.6.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/spire-math/jawn-parser_2.10/0.6.0/jawn-parser_2.10-0.6.0.pom";
      sha256 = "1shmrq62mg2p12sadgwj1bp0yr5fx24byqjw8g5v245syqbgvgri";
    };
    "nix-public/org/spire-math/json4s-support_2.10/0.6.0/json4s-support_2.10-0.6.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/spire-math/json4s-support_2.10/0.6.0/json4s-support_2.10-0.6.0.jar";
      sha256 = "0nilfi5k1smnl3df94xzf2zd6cddisnp8xfyn7mfn4h7r7sq0l0d";
    };
    "nix-public/org/spire-math/json4s-support_2.10/0.6.0/json4s-support_2.10-0.6.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/spire-math/json4s-support_2.10/0.6.0/json4s-support_2.10-0.6.0.pom";
      sha256 = "09x0xr7bvmsbicflz3qzc9fw2afpx9k37y2dwvp46myyscbm1pji";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/actions/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/actions/0.13.15/ivys/ivy.xml";
      sha256 = "077i34n5nps0lr48zq6h43iyr2xicxkr560l5r47ak4vizp0y9gf";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/actions/0.13.15/jars/actions.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/actions/0.13.15/jars/actions.jar";
      sha256 = "0hanwi44rgf5j63bachna7fmsgabn2d4gq9kb196f8y9iknf6va6";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/api/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/api/0.13.15/ivys/ivy.xml";
      sha256 = "142kb4a84070m7pfj7p5cqrapxqzhk2hw6fhhrf5nwmxklf8czac";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/api/0.13.15/jars/api.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/api/0.13.15/jars/api.jar";
      sha256 = "1pnfmfxbhybxn5x5b8v5071h7nxv6sw0fff12r4brkh22c7pyvkj";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/apply-macro/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/apply-macro/0.13.15/ivys/ivy.xml";
      sha256 = "0aivff8qc99jzw7i3yncdxzxmbpjci0bkxla216l63w7izclyshy";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/apply-macro/0.13.15/jars/apply-macro.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/apply-macro/0.13.15/jars/apply-macro.jar";
      sha256 = "188639ddvzw64gp9w64ff9j57v6nlwfc9wrqqsa8rwwxr92n3k89";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/cache/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/cache/0.13.15/ivys/ivy.xml";
      sha256 = "10q7fcmqdvzmixyi14y7pxbhfp4k17nv4ysar2q25f85hklfdb94";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/cache/0.13.15/jars/cache.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/cache/0.13.15/jars/cache.jar";
      sha256 = "01zkiqzxbxl6jq4zcn66q0b5v2nx8sn4415rvv98gs27g6k3vbh1";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/classfile/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/classfile/0.13.15/ivys/ivy.xml";
      sha256 = "0dgwlkqhffp70cihad92rlammrm8hf22aj7snqqv76aaxpl5baip";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/classfile/0.13.15/jars/classfile.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/classfile/0.13.15/jars/classfile.jar";
      sha256 = "0bk0r0hjkknn4zqyamn1hfak316bikvzw3x6mc6p9d35nds4qd7n";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/classpath/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/classpath/0.13.15/ivys/ivy.xml";
      sha256 = "1y7k5napxb54m5191rjky25ljagqwidrlyxx439jhpdbwd733vv1";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/classpath/0.13.15/jars/classpath.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/classpath/0.13.15/jars/classpath.jar";
      sha256 = "1d6j3krn1ykl858njvmznc7m49kszcd4hyx04i0a0zldnsrz44zh";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/collections/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/collections/0.13.15/ivys/ivy.xml";
      sha256 = "1nl6xkch5dfv9nxj0s6gyb7c37yx4pqm7v11c1mz0p69jrbvgq7k";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/collections/0.13.15/jars/collections.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/collections/0.13.15/jars/collections.jar";
      sha256 = "1c489xcmxn2600wfcsl6rk1drwf7qwp3499ka8d66fzc97m41h36";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/command/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/command/0.13.15/ivys/ivy.xml";
      sha256 = "1qmsphfxswclhbhc926zqg7iyx19ilgdswfx9vafns1v7hd1vmps";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/command/0.13.15/jars/command.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/command/0.13.15/jars/command.jar";
      sha256 = "0gg0fhrppmr74gzxbqwjq6xh3v9i61yzsr68id5khhlnhbm5p6w3";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/compile/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compile/0.13.15/ivys/ivy.xml";
      sha256 = "0j2v89gcsqfl7fq5mbmnfmifp6d09zic0aj0g0k79dl6106pqj0p";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/compile/0.13.15/jars/compile.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compile/0.13.15/jars/compile.jar";
      sha256 = "0wd1b3b1g8l11y9qdikl0w0s4qd2hgshgnc2j4a3ypz0dfvgq020";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/compiler-integration/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-integration/0.13.15/ivys/ivy.xml";
      sha256 = "1i2rb08dc1yvy8rqzxcyycnh3zy1m7bk2d06gz46983qgncz089i";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/compiler-integration/0.13.15/jars/compiler-integration.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-integration/0.13.15/jars/compiler-integration.jar";
      sha256 = "1jbcfdahf1af7d6a8h6rxnfjzrfdbm2p20pwvmn8sp79a5bwrgwp";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/compiler-interface/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-interface/0.13.15/ivys/ivy.xml";
      sha256 = "0jzjwls4hcw150xcdc8indfmvd9124vwd2dbnwxnrq0ga2cahxb0";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/compiler-interface/0.13.15/jars/compiler-interface.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-interface/0.13.15/jars/compiler-interface.jar";
      sha256 = "1m8zmm53dmmcrq18fmg8iljgv367s3jsg7acmpg3h87zkna6cgjf";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/compiler-ivy-integration/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-ivy-integration/0.13.15/ivys/ivy.xml";
      sha256 = "0vc30r2mfh3kxy5xvay4yqwbi99i6phw8jgjr7rzrw6ahkdzz83s";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/compiler-ivy-integration/0.13.15/jars/compiler-ivy-integration.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-ivy-integration/0.13.15/jars/compiler-ivy-integration.jar";
      sha256 = "0hjazxg2g7zgh912dj1n79jhgqqpv135x068scrhzv82jjw20rlh";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/completion/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/completion/0.13.15/ivys/ivy.xml";
      sha256 = "08w814igsraq4xi9d5f6rcc1w5ki22fv202xzik8h60xczjark5x";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/completion/0.13.15/jars/completion.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/completion/0.13.15/jars/completion.jar";
      sha256 = "11f3vyzk6xx8iarnpnkmcfsj8rmrik8gmyymd7jdmjjbik7895rp";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/control/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/control/0.13.15/ivys/ivy.xml";
      sha256 = "044s4v0r11r13sds041nzgr8a0v2kmp48w89254zmaaddmw0h2zq";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/control/0.13.15/jars/control.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/control/0.13.15/jars/control.jar";
      sha256 = "0nfi9bhmgqyv3wh64v73pf2vl0pj2mnyknj9r895xgrpr2sck27b";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/cross/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/cross/0.13.15/ivys/ivy.xml";
      sha256 = "14xnkmswqy8brln4jqgcig863ml2a0yyzvm8h5wbd1w3ah62hi96";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/cross/0.13.15/jars/cross.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/cross/0.13.15/jars/cross.jar";
      sha256 = "08bmpwqxhpbypf3lxm1ns2s1fwn6hfz30xl0n3d8lf9slgd8s2k7";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/incremental-compiler/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/incremental-compiler/0.13.15/ivys/ivy.xml";
      sha256 = "1albbxqv13sjbpk6jc37hdai3cz57z7d1jk76p9638xs4wmzdyna";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/incremental-compiler/0.13.15/jars/incremental-compiler.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/incremental-compiler/0.13.15/jars/incremental-compiler.jar";
      sha256 = "145iys4v1bnpbbh4y9xpbk730f0i243amv3x7w22hkikypl7hbli";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/interface/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/interface/0.13.15/ivys/ivy.xml";
      sha256 = "08ipf8zgmrsp6rjy6hi1jiiwqq8dym5fcfggqwm3wz1zdp90iqpa";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/interface/0.13.15/jars/interface.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/interface/0.13.15/jars/interface.jar";
      sha256 = "1arpbcsfjn21r00v1sgyafqdbmirh2q2zdj63rcwxwyw6y6i7g4l";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/io/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/io/0.13.15/ivys/ivy.xml";
      sha256 = "0zfds598bp62vv7vivjxjs1kkpnhgai7km7kdkg6ci2snvx0aija";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/io/0.13.15/jars/io.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/io/0.13.15/jars/io.jar";
      sha256 = "1qn8lnxxvgsv8p004dyq6272r5zxrgz5whf616w4819mxck9aq99";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/ivy/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/ivy/0.13.15/ivys/ivy.xml";
      sha256 = "00byzwf657483fjbb67lzkv9yyvsaw8q8lqcqnc1yhqr4p7cbnr5";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/ivy/0.13.15/jars/ivy.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/ivy/0.13.15/jars/ivy.jar";
      sha256 = "0h9vhhkr0qi5ygkxz7wvsi3g421r0a0amwgv75dmwmdxl25xr6l4";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/logging/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/logging/0.13.15/ivys/ivy.xml";
      sha256 = "0lwrrag9l6dnyxxcc0w3rx7dkws6pcdvrs88xb8bhq5218mlr5n9";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/logging/0.13.15/jars/logging.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/logging/0.13.15/jars/logging.jar";
      sha256 = "1paad0m3cj5kzpxpr1q674shdwr7xaxk6alhn92r6p9ikq5dr53j";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/logic/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/logic/0.13.15/ivys/ivy.xml";
      sha256 = "1hz68kw64an09vr82jql0vis2g7q9675mmn7467i1my7y56bdl3h";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/logic/0.13.15/jars/logic.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/logic/0.13.15/jars/logic.jar";
      sha256 = "1ia8d9ajwgrk91dyj05mh61z84v87pynq2jk46q1fnqlj5dins7j";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/main-settings/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main-settings/0.13.15/ivys/ivy.xml";
      sha256 = "0w3iafa1h70kzzg2mm2h4pds7wchqzbmisnzsj352b3dwq6sg9b7";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/main-settings/0.13.15/jars/main-settings.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main-settings/0.13.15/jars/main-settings.jar";
      sha256 = "0rv93nf83pbr96n1hiqx31f8zc6ghqbwn7gmvxaqaf9msnplfbpw";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/main/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.15/ivys/ivy.xml";
      sha256 = "0hh2dgvdkdjkb6482kidlnwsmci84qwml7q69bc2ys2lsf9vabmz";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/main/0.13.15/jars/main.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.15/jars/main.jar";
      sha256 = "0c85xawfli71mf52wcxzf4vs68jp0287s3q2fppcn30vgp1pawmw";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/persist/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/persist/0.13.15/ivys/ivy.xml";
      sha256 = "100czcx8lh0nx0s2lpbvl7z06r8swbh5k95ml1x6wy57vgg5p36b";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/persist/0.13.15/jars/persist.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/persist/0.13.15/jars/persist.jar";
      sha256 = "0wlciddm33qg768ihfa88xri0235zg18f8faiv8dmwxz67xpby2k";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/process/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/process/0.13.15/ivys/ivy.xml";
      sha256 = "15w5sm9f5ny1xz2z38zfapanhbcw5pra0989mizgfqrap4bv728r";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/process/0.13.15/jars/process.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/process/0.13.15/jars/process.jar";
      sha256 = "12rnn85sdzrl9gagdz7d747zx5ghj109n0n4xziw2zlrq7h35vjx";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/relation/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/relation/0.13.15/ivys/ivy.xml";
      sha256 = "00ddj6y1gnijs5s3m1bk0i1133gf5c75rs70fjqzrxjdyw2rlwv6";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/relation/0.13.15/jars/relation.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/relation/0.13.15/jars/relation.jar";
      sha256 = "1ga5zx7s9p0jyzr4bamap1zzxqnpvmhky3b7vzdb5gsjgybf4np7";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/run/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/run/0.13.15/ivys/ivy.xml";
      sha256 = "02h1v95fhl8654ydqxqjw4s62dlrfrvmncpvqvz2pgrsk8jjlbsq";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/run/0.13.15/jars/run.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/run/0.13.15/jars/run.jar";
      sha256 = "099r2krnkmfyx0cdm8bylxrxk0znfx8g5rjq0wyh857l915x72hc";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/sbt/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.15/ivys/ivy.xml";
      sha256 = "19r0ppirpxy521q82xy0vq2ky8lsg20ndp14v7nmwpfc2bid6mb5";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/sbt/0.13.15/jars/sbt.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.15/jars/sbt.jar";
      sha256 = "0jqbga8qdv8a2l2amxd6mbyqj16s73biyraan1q5rdkyd3i0s3lh";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/scripted-plugin/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/scripted-plugin/0.13.15/ivys/ivy.xml";
      sha256 = "1xxqdbr26gd6rsqdk6agnckd1v9823sarmrc1qzd6l5dbcpw6djv";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/scripted-plugin/0.13.15/jars/scripted-plugin.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/scripted-plugin/0.13.15/jars/scripted-plugin.jar";
      sha256 = "0f88zg1iam0icadjyvhby04sngj3c914pdr26p11gjx8v23df8k0";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/task-system/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/task-system/0.13.15/ivys/ivy.xml";
      sha256 = "1778b2hjnwb11rqalbl5sccxhb63q0d139drppw8166mky9hagfs";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/task-system/0.13.15/jars/task-system.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/task-system/0.13.15/jars/task-system.jar";
      sha256 = "0hq0isj2cdzpli4qsdnvbnkc6km0dznv9sr2b84a4pn7kyv47wp2";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/tasks/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/tasks/0.13.15/ivys/ivy.xml";
      sha256 = "1ipnbjjnr2h96rkl04zm7rw4dv27irqnd7dddx6bghj5k67jq20v";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/tasks/0.13.15/jars/tasks.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/tasks/0.13.15/jars/tasks.jar";
      sha256 = "1mr0ahqnx1wwcwk08krpvrvr9nsxwhcwcja91hnyy40gdlj79bjg";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/test-agent/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/test-agent/0.13.15/ivys/ivy.xml";
      sha256 = "0y8ppz2fi8krccr2m3nc7igyqnxll70wchf44ps874a9hjlvlfjn";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/test-agent/0.13.15/jars/test-agent.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/test-agent/0.13.15/jars/test-agent.jar";
      sha256 = "0s7512bzfajqlcm817p6l5gnmi6zp81amhgz527qn6p6m1l85qzb";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/testing/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/testing/0.13.15/ivys/ivy.xml";
      sha256 = "1h50cbpgxmm9fpsiynni0lvhmgs1gdhan3j6k3hah5iv6x1yradk";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/testing/0.13.15/jars/testing.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/testing/0.13.15/jars/testing.jar";
      sha256 = "04bndxmaah5hw60hpplg2lj1sns8f8yi6rpmr33mrsxjamh3vhni";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/tracking/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/tracking/0.13.15/ivys/ivy.xml";
      sha256 = "0wzf37isnh3h748hwcpbr5qglp52jzm9hdpg5c1svyasbsp1856b";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/tracking/0.13.15/jars/tracking.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/tracking/0.13.15/jars/tracking.jar";
      sha256 = "0fa53k7621xg25zyy9dyd14szvj1w9qrh8pdw6w4pq8vlx5jzfjx";
    };
    "nix-typesafe-ivy-releases/org.scala-tools.sbinary/sbinary_2.10/0.4.2/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-tools.sbinary/sbinary_2.10/0.4.2/ivys/ivy.xml";
      sha256 = "1xyjxg6s5nfzb6xjmx5lxcymj79l5gmfcrfk2bnj7ycq7k5hva6g";
    };
    "nix-typesafe-ivy-releases/org.scala-tools.sbinary/sbinary_2.10/0.4.2/jars/sbinary_2.10.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-tools.sbinary/sbinary_2.10/0.4.2/jars/sbinary_2.10.jar";
      sha256 = "0qhk0ldkkqknqbq5f3gh81f48fpi1fivf1dj880156r80fvrd8nl";
    };
  };
}
